title: Peruzzo.Net
description: 'Fabio Peruzzo Barbosa''s personal website'
url: 'https://peruzzo.net'
google_analytics: 
show_downloads: false
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 
