title: Peruzzo.Net
description: 'Fabio Peruzzo Barbosa''s personal website'
url: 'https://peruzzo.net'
google_analytics: 
show_downloads: false
# theme: jekyll-theme-cayman
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

author:
  name: 'Fabio Peruzzo Barbosa'
  email: peruzzo@gmail.com
  twitter_username: peruzzof
  #facebook_username: joshgerdes
  github_username:  peruzzof
  linkedin_username:  peruzzo
  #meetup_name: Azure-Meetup-Rostock-MV

# gems:
#   - jekyll-mentions